#!/bin/sh
if [ -z $SCRIPT_PATH ]; then SCRIPT_PATH=$(dirname $0); fi
. $SCRIPT_PATH/serval-vars
. $SCRIPT_PATH/serval-base

if [ "$1" = "-h" ]; then
    echo "creates csv dump for disk usage to $MONITOR_PATH"
    exit 0
fi

# using latest monitoring path
MONITOR_PATH=`ls -td -- $MONITOR_PATH/*/ | grep 20 | head -n 1`
OUTFILE=$(echo "$MONITOR_PATH/diskusage/diskusage-$(hostname).csv" | sed s#//*#/#g)

echo "timestamp,filesystem,size,used,available,use%,mounted" > $OUTFILE

while [ true ]; do
    sleep $SLEEP_TIME

    df -P | awk '{if(NR>1)print systime()","$1","$2","$3","$4","$5","$6}' >> $OUTFILE
done
