#!/bin/sh
if [ -z $SCRIPT_PATH ]; then SCRIPT_PATH=$(dirname $0); fi
. $SCRIPT_PATH/serval-vars

usage() {
    echo "usage: $0 <count> [output_path]"
    echo "generates <count> times 5 files at [output_path] or \$TESTFILE_PATH"
}

if [ -z $1 ]; then usage; exit 1; fi
if [ "$1" = "-h" ]; then usage; exit 0; fi
if ! [ -z $2 ]; then TESTFILE_PATH=$2; fi

mkdir -p $TESTFILE_PATH

echo "generating files in $TESTFILE_PATH"

for cnt in `seq 1 $1`; do
    echo "generating files: $cnt / $1..."
    dd if=/dev/urandom of=$TESTFILE_PATH/0.25k-$cnt.file bs=1K count=256
    dd if=/dev/urandom of=$TESTFILE_PATH/0.5k-$cnt.file bs=1K count=512
    dd if=/dev/urandom of=$TESTFILE_PATH/1m-$cnt.file bs=1M count=1
    dd if=/dev/urandom of=$TESTFILE_PATH/5m-$cnt.file bs=1M count=5
    dd if=/dev/urandom of=$TESTFILE_PATH/10m-$cnt.file bs=1M count=10
done

echo "Done!"
