#!/bin/sh
if [ -z $SCRIPT_PATH ]; then SCRIPT_PATH=$(dirname $0); fi
. $SCRIPT_PATH/serval-vars
. $SCRIPT_PATH/serval-base

if [ "$1" = "-h" ]; then
    echo "writes a csv dump for meshms properties (inserttime, sender, recipient) to $MONITOR_PATH"
    exit 0
fi

MONITOR_PATH="$MONITOR_PATH/$(date +%Y-%m-%d_%H-%M)"
OUTFILE="$MONITOR_PATH/rhizome_inserted_-$(hostname).csv"
mkdir -p $MONITOR_PATH
echo "timestamp_ms,sender,recipient" > $OUTFILE

tail -f -n+1 /home/meshadmin/serval-conf/var/log/serval.log | grep --line-buffered 'rhizome_store_manifest()  INSERT OR REPLACE.*MeshMS' | awk {'split($10,a,","); print a[4] "," a[11] "," a[12]'} >> $OUTFILE
