#!/bin/sh
if [ "$1" = "-h" ]; then
    echo "usage: $0"
    echo "initiates a serval scan for all local inet addrs"
fi

for i in `ifconfig | grep "inet addr:10." | cut -d":" -f 2 | cut -d"." -f1,2,3`; do
    servald scan $i.255
done
