#!/bin/sh
if [ -z $SCRIPT_PATH ]; then SCRIPT_PATH=$(dirname $0); fi
. $SCRIPT_PATH/serval-base

if [ "$1" = "-h" ]; then
    echo "Sends a message to every SID in $SEVERAL_ALL_SIDS_FILE"
    exit 0
fi

# using latest monitoring path
MONITOR_PATH=`ls -td -- $MONITOR_PATH/*/ | grep 20 | head -n 1`
OUTFILE=$(echo "$MONITOR_PATH/active/meshms-hello-eveybody-active-$(hostname).csv" | sed s#//*#/#g)

if ! [ -e $OUTFILE ]; then
	echo "timestamp,sender,recipient" > $OUTFILE
fi

for their_sid in $(cat $SEVERAL_ALL_SIDS_FILE); do
    if [ "$their_sid" = "$SID" ]; then
	continue
    fi
    echo "`date +%s`,$SID,$their_sid" >> $OUTFILE
    echo "Sending MeshMS to $their_sid"
    /serval-tests/meshms-send-curl $SID $their_sid "Convinced myself, I seek not to convince. $(date +%s)"
done
