#!/bin/sh
. $SCRIPT_PATH/serval-vars
. $SCRIPT_PATH/serval-base

mkdir -p $LOG_PATH
OUTFILE="$LOG_PATH/meshms-$(date +%s)-$(hostname).csv"
echo "timestamp_ms,my_conv_count,total_conv_count,meshms_bytes" | tee -a $OUTFILE

while [ true ]; do
    sleep $SLEEP_TIME
    NOW=$(date_ms)
    MY_COUNT=$(( $(servald meshms list conversations $SID | wc -l) -2 ))
    TOTAL_COUNT=$(sqlite3 $RHIZOME_STORE_PATH/rhizome.db <<< 'select count(MANIFESTS.filesize) from MANIFESTS where MANIFESTS.service = "MeshMS2";')
    MESHMS_BYTES=$(sqlite3 $RHIZOME_STORE_PATH/rhizome.db <<< 'select total(MANIFESTS.filesize) from MANIFESTS where MANIFESTS.service = "MeshMS2";')
    echo "$NOW,$MY_COUNT,$TOTAL_COUNT,$MESHMS_BYTES" | tee -a $OUTFILE
done
