#!/bin/sh
if [ -z $SCRIPT_PATH ]; then SCRIPT_PATH=$(dirname $0); fi
. $SCRIPT_PATH/serval-vars
. $SCRIPT_PATH/serval-base

if [ "$1" = "-h" ]; then
    echo "writes a csv dump for selected meshms properties to $MONITOR_PATH"
    exit 0
fi

# using latest monitoring path
MONITOR_PATH=`ls -td -- $MONITOR_PATH/*/ | grep 20 | head -n 1`
OUTFILE="$MONITOR_PATH/meshms-$(hostname).csv"

echo "timestamp_ms,my_conv_count,total_conv_count,meshms_bytes" > $OUTFILE

while [ true ]; do
    sleep $SLEEP_TIME
    
    NOW=$(date_ms)
    MY_COUNT=$(( $(servald meshms list conversations $SID | wc -l) -2 ))
    # TOTAL_COUNT=$(echo 'select count(MANIFESTS.filesize) from MANIFESTS where MANIFESTS.service = "MeshMS2";' | sqlite3 $RHIZOME_STORE_PATH/rhizome.db)
    # MESHMS_BYTES=$(echo 'select total(MANIFESTS.filesize) from MANIFESTS where MANIFESTS.service = "MeshMS2";' | sqlite3 $RHIZOME_STORE_PATH/rhizome.db)
    
    echo "$NOW,$MY_COUNT,$TOTAL_COUNT,$MESHMS_BYTES" >> $OUTFILE
done
