#!/bin/sh
if [ -z $SCRIPT_PATH ]; then SCRIPT_PATH=$(dirname $0); fi
. $SCRIPT_PATH/serval-vars
. $SCRIPT_PATH/serval-base

if [ "$1" = "-h" ]; then
    echo "follows serval.log and creates csv dump for meshms insertions to $MONITOR_PATH"
    exit 0
fi

MONITOR_PATH="$MONITOR_PATH/$(date +%Y-%m-%d_%H-%M)"
OUTFILE="$MONITOR_PATH/meshms-insertion-$(hostname).csv"
mkdir -p $MONITOR_PATH
echo "timestamp_ms,sender,recipient,text" > $OUTFILE

exec $SCRIPT_PATH/meshms-insertion.py >> $OUTFILE
