#!/bin/sh

SENDER=$1
RECIPIENT=$2
MESSAGE=$3

curl \
	-H "Expect:" \
	--silent --fail --show-error \
	--basic --user harry:potter \
	--form "message=$MESSAGE;type=text/plain;charset=utf-8" \
	"http://127.0.0.1:4110/restful/meshms/$SENDER/$RECIPIENT/sendmessage"
