#!/bin/sh
if [ -z $SCRIPT_PATH ]; then SCRIPT_PATH=$(dirname $0); fi
. $SCRIPT_PATH/serval-vars

usage() {
    echo "usage:"
    echo "  $0 system    start logging of serval, rhizome and meshms"
    echo "  $0 serval    start logging of serval, rhizome and meshms"
    echo "  $0 stop      stop logging; parse serval logs"
    echo "  $0 help      show this help message"
}

if [ -z $1 ]; then
    usage
    exit 1
fi

HOSTNAME=$(hostname)

if [ "$1" = "system" ]; then
    mkdir -p $MONITOR_PATH/log/ 
    
    nohup $SCRIPT_PATH/pidstat-monitor > $MONITOR_PATH/log/pidstat-monitor-$HOSTNAME.err 2>&1 &
    PIDS="$PIDS $!"
    
    for IF in $(ls -1 /sys/class/net); do
        if [ "$IF" = "lo" ]; then continue; fi
        nohup $SCRIPT_PATH/net-monitor $IF > $MONITOR_PATH/log/net-monitor-$HOSTNAME@$IF.err 2>&1 &
        PIDS="$PIDS $!"
    done
    
    # sleep a second to allow processes to start
    # sleep 1
    
    echo -n " $PIDS" >> $MONITOR_PATH/$HOSTNAME.pids
    exit 0
fi

if [ "$1" = "serval" ]; then
    . $SCRIPT_PATH/serval-base
    mkdir -p $MONITOR_PATH/log/
    
    mkdir -p $MONITOR_PATH/$(date +%Y-%m-%d_%H-%M)
    servald id self | tail -n 1 > $MONITOR_PATH/$(date +%Y-%m-%d_%H-%M)/$HOSTNAME.sid 2>&1

    nohup $SCRIPT_PATH/servald-monitor > $MONITOR_PATH/log/servald-monitor-$HOSTNAME.err 2>&1 &
    PIDS="$PIDS $!"

    nohup $SCRIPT_PATH/rhizome-monitor > $MONITOR_PATH/log/rhizome-monitor-$HOSTNAME.err 2>&1 &
    PIDS="$PIDS $!"

    nohup $SCRIPT_PATH/meshms-monitor > $MONITOR_PATH/log/meshms-monitor-$HOSTNAME.err 2>&1 &
    PIDS="$PIDS $!"

    # sleep a second to allow processes to start
    # sleep 1
    
    echo -n " $PIDS" >> $MONITOR_PATH/$HOSTNAME.pids
    exit 0
fi

if [ "$1" = "stop" ]; then
    . $SCRIPT_PATH/serval-base
    # echo node $HOSTNAME, killing `cat $MONITOR_PATH/$HOSTNAME.pids`
    # ps aux
    kill `cat $MONITOR_PATH/$HOSTNAME.pids`
    rm $MONITOR_PATH/$HOSTNAME.pids
    
    # using latest monitoring path
    LATEST_MONITOR_PATH=`ls -td -- $MONITOR_PATH/*/ | grep 20 | head -n 1`
    cp -R `servald config paths | grep SERVAL_LOG_PATH | cut -d ":" -f2` $LATEST_MONITOR_PATH/serval-logs-$HOSTNAME
    
    $SCRIPT_PATH/rhizome-insertion-monitor > $MONITOR_PATH/log/rhizome-insertion-monitor-$HOSTNAME.err 2>&1
    $SCRIPT_PATH/rhizome-direct-insertion-monitor > $MONITOR_PATH/log/rhizome-direct-insertion-monitor-$HOSTNAME.err 2>&1
    $SCRIPT_PATH/meshms-insertion-monitor > $MONITOR_PATH/log/meshms-insertion-monitor-$HOSTNAME.err 2>&1
    $SCRIPT_PATH/meshms-log-monitor > $MONITOR_PATH/log/meshms-log-monitor-$HOSTNAME.err 2>&1
    
    exit 0
fi

if [ "$1" = "help" ]; then
    usage
    exit 0
fi

echo "unknown command: $1"
usage
exit 1
