#!/bin/sh
if [ -z $SCRIPT_PATH ]; then SCRIPT_PATH=$(dirname $0); fi

usage() {
    echo "usage:"
    echo "  $0 start     start logging of serval, rhizome and meshms"
    echo "  $0 stop      stop logging"
    echo "  $0 help      show this help message"
}

if [ -z $1 ]; then
    usage
    exit 1
fi

if [ "$1" = "start" ]; then
    mkdir -p $MONITOR_PATH/run
    mkdir -p $MONITOR_PATH/log

    $SCRIPT_PATH/servald-monitor &
    echo $! > $MONITOR_PATH/run/servald-monitor-$HOSTNAME.pid > /dev/null 2> $MONITOR_PATH/log/servald-monitor-$HOSTNAME.err
    $SCRIPT_PATH/rhizome-monitor &
    echo $! > $MONITOR_PATH/run/rhizome-monitor-$HOSTNAME.pid > /dev/null 2> $MONITOR_PATH/log/rhizome-monitor-$HOSTNAME.err
    $SCRIPT_PATH/meshms-monitor &
    echo $! > $MONITOR_PATH/run/meshms-monitor-$HOSTNAME.pid > /dev/null 2> $MONITOR_PATH/log/meshms-monitor-$HOSTNAME.err
    exit 0
fi

if [ "$1" = "stop" ]; then
    kill `cat $MONITOR_PATH/run/servald-monitor-$HOSTNAME.pid`
    rm $MONITOR_PATH/run/servald-monitor-$HOSTNAME.pid
    kill `cat $MONITOR_PATH/run/rhizome-monitor-$HOSTNAME.pid`
    rm $MONITOR_PATH/run/rhizome-monitor-$HOSTNAME.pid
    kill `cat $MONITOR_PATH/run/meshms-monitor-$HOSTNAME.pid`
    rm $MONITOR_PATH/run/meshms-monitor-$HOSTNAME.pid
    exit 0
fi

if [ "$1" = "help" ]; then
    usage
    exit 0
fi

echo "unknown command: $1"
usage
exit 1