#!/bin/sh
if [ -z $SCRIPT_PATH ]; then SCRIPT_PATH=$(dirname $0); fi
. $SCRIPT_PATH/serval-vars

if [ "$1" = "-h" ]; then
    echo "writes a csv dump for network traffic to $MONITOR_PATH"
    echo "usage:   $0 ifname"
    exit 0
fi

if [ -z $1 ]; then
    echo "Error: missing parameter 1"
    echo "usage: $0 ifname"
    exit 1
fi
    
# using latest monitoring path
MONITOR_PATH=`ls -td -- $MONITOR_PATH/*/ | grep 20 | head -n 1`
OUTFILE=$(echo "$MONITOR_PATH/netmon/netmon-$(hostname)@$1.csv" | sed s#//*#/#g)

exec python $SCRIPT_PATH/netmon.py $1 > $OUTFILE
