#!/bin/sh
if [ -z $SCRIPT_PATH ]; then SCRIPT_PATH=$(dirname $0); fi
. $SCRIPT_PATH/serval-vars

if [ "$1" = "-h" ]; then
    echo "writes a csv dump for servald pidstat properties to $MONITOR_PATH"
    exit 0
fi

# using latest monitoring path
MONITOR_PATH=`ls -td -- $MONITOR_PATH/*/ | grep 20 | head -n 1`
OUTFILE="$MONITOR_PATH/pidstat-$(hostname).csv"

pidstat -druh -p ALL | sed '1d;/^$/d;s/#[ ]*Time/timestamp/g;s/^[ ]*//;s/[ ]\+/,/g' | head -n 1 > $OUTFILE

while [ true ]; do
    sleep $SLEEP_TIME
    
    pidstat -druh -p ALL -C "servald" | sed '1d;/^[#]/d;/^$/d;s/^[ ]*//;s/[ ]\+/,/g' >> $OUTFILE
done
