#!/bin/sh
if [ -z $SCRIPT_PATH ]; then SCRIPT_PATH=$(dirname $0); fi
. $SCRIPT_PATH/serval-vars
. $SCRIPT_PATH/serval-base

if [ "$1" = "-h" ]; then
    echo "follows serval.log and creates csv dump for rhizome insertions to $MONITOR_PATH"
    exit 0
fi

NEWEST_MONITOR_PATH=`ls -td -- $MONITOR_PATH/* | head -n 1`
MONITOR_PATH="$NEWEST_MONITOR_PATH"
OUTFILE="$MONITOR_PATH/rhizome-direct-insertion-$(hostname).csv"
mkdir -p $MONITOR_PATH
echo "_id:service:id:version:date:timestamp_ms:.author:.fromhere:filesize:filehash:sender:recipient:name" > $OUTFILE

exec $SCRIPT_PATH/rhizome-direct-insertion.py >> $OUTFILE
