#! /bin/bash

manifest_file="/tmp/`hostname`.man"
touch $manifest_file

curl -H "Expect:" \
     --silent --show-error \
     --basic --user harry:potter \
     --form "manifest=@$manifest_file;type=rhizome/manifest;format=\"text+binarysig\"" \
     --form "payload=@$1;filename=\"$1\"}" \
     "http://127.0.0.1:4110/restful/rhizome/insert"
     
rm $manifest_file
