#! /bin/bash

curl -H "Expect:" \
     --silent --show-error \
     --basic --user harry:potter \
     --form "manifest=@$1;type=rhizome/manifest;format=\"text+binarysig\"" \
     --form "payload=@$2;filename=\"$2\"}" \
     "http://127.0.0.1:4110/restful/rhizome/insert"
