#!/bin/sh
if [ -z $SCRIPT_PATH ]; then SCRIPT_PATH=$(dirname $0); fi
. $SCRIPT_PATH/serval-vars
. $SCRIPT_PATH/serval-base

if [ "$1" = "-h" ]; then
    echo "follows serval.log and creates csv dump for rhizome insertions to $MONITOR_PATH"
    exit 0
fi


# using latest monitoring path
MONITOR_PATH=`ls -td -- $MONITOR_PATH/*/ | grep 20 | head -n 1`
OUTFILE="$MONITOR_PATH/rhizome-insertion-$(hostname).csv"
echo "id,manifest,version,timestamp_ms,bar,filesize,filehash,author,service,name,sender,recipient,tail,manifest_hash" > $OUTFILE

exec $SCRIPT_PATH/rhizome-insertion.py $SYSTEM_LOG_PATH/serval/ >> $OUTFILE
