#!/bin/sh
if [ "$1" = "-h" ]; then
    echo "Lists number and and names of files in Rhizome store."
    exit 0
fi

echo Total files in Rhizome Store: $(servald rhizome list | grep ":file": | wc -l)
echo
servald rhizome list | grep ":file": | cut -d":" -f 13
