#!/bin/sh
if [ -z $SCRIPT_PATH ]; then SCRIPT_PATH=$(dirname $0); fi
. $SCRIPT_PATH/serval-vars
. $SCRIPT_PATH/serval-base

if [ "$1" = "-h" ]; then
    echo "follows serval.log and creates csv dump for rhizome insertions to $MONITOR_PATH"
    exit 0
fi

MONITOR_PATH="$MONITOR_PATH/$(date +%Y-%m-%d_%H-%M)"
OUTFILE="$MONITOR_PATH/rhizome-insertion-$(hostname).csv"
mkdir -p $MONITOR_PATH
echo "timestamp_ms,filename,filehash" > $OUTFILE

tail -f -n+1 $SYSTEM_LOG_PATH/serval.log | grep --line-buffered 'rhizome_store_manifest()  INSERT OR REPLACE.*file' | awk '{split($10,a,","); if(a[10] != "NULL" && a[10] != "'\'\''"){ print a[4] "," a[10] "," a[7]}; fflush(stdout)'} >> $OUTFILE
