#!/bin/bash
. $SCRIPT_PATH/serval-vars
. $SCRIPT_PATH/serval-base

mkdir -p $LOG_PATH
OUTFILE="$LOG_PATH/servald-$(date +%s)-$(hostname).csv"
echo "timestamp_ms,peer_count" | tee -a $OUTFILE

while [ true ]; do
    sleep $SLEEP_TIME
    NOW=$(date_ms)
    COUNT=$(servald peer count)
    echo "$NOW,$COUNT" | tee -a $OUTFILE
done
